### ISSUE TITLE
8.4.3.0 number_format_exception

### ISSUE THREAD

**Issue by sigurdblueface** [mindw/elasticsearch-prometheus-exporter#15]
Hello, sorry, but could you please advise me what could go wrong here:

I've just installed 8.4.3.0 plugin 
```
root@elastic-data-2:/home/user# curl localhost:9200/_cat/plugins
data-node-2 prometheus-exporter 8.4.3.0
```
and I'm getting:
```
root@elastic-data-2:/home/user# curl localhost:9200/_prometheus/metrics
{"error":{"root_cause":[{"type":"number_format_exception","reason":"For input string: \"max\""}],"type":"number_format_exception","reason":"For input string: \"max\""},"
```

many thanks in advance

**Comment by mindw** [comment]
@sigurdblueface thanks for the report!

Any chance you can add the server log as well? that should point to the offending line.

**Comment by mindw** [comment]
@sigurdblueface thanks for the log it helped to pin point the issue!

It seems CgroupsV2 allows the value `max` for `memory.max` which causes the fault. Test don't catch it as they are not run in such an env as used above.
I'm testing a workaround and hopefully will a new version in a day or two.

**Comment by mindw** [comment]
@sigurdblueface my apologies for taking more time than estimated - please check the latest release:
https://github.com/mindw/elasticsearch-prometheus-exporter/releases/tag/8.4.3.1

**Comment by sigurdblueface** [comment]
@mindw thanks a lot, new version works perfectly.
