### ISSUE TITLE
Generate release for elasticsearch 8.5.x

### ISSUE THREAD

**Issue by MikeKlebolt** [mindw/elasticsearch-prometheus-exporter#18]
We're looking to bump our elasticsearch  image version to 8.5.x to address several vulnerabilities that are present in the 8.5.x image.  Would it be possible for you to create an `elasticsearch-prometheus-exporter` release to match the latest elasticsearch version?

Thanks!

**Comment by mindw** [comment]
During the weekend. 8.5 introduced some new metrics which I would like to expose.

**Comment by mindw** [comment]
@MikeKlebolt 8.5.x up to 8.5.2 releases are now available. ES 8.5.3 was tagged but it isn't available to build against yet.

Thanks for being patient 🌹

**Comment by MikeKlebolt** [comment]
No worries at all.  I greatly appreciate you taking care of this.
