### ISSUE TITLE
Release for 8.7.0

### ISSUE THREAD

**Issue by Philippus** [mindw/elasticsearch-prometheus-exporter#27]
Elasticsearch 8.7.0 got released: https://www.elastic.co/guide/en/elasticsearch/reference/8.7/release-notes-8.7.0.html.

**Comment by mindw** [comment]
yes, I'll get to during the weekend :)

**Comment by mindw** [comment]
Done in https://github.com/mindw/elasticsearch-prometheus-exporter/commit/3e5c5177bd135bc30a8404deb796ba6aa584329f

Please report any issues :)
