### ISSUE TITLE
Release for 8.8.0

### ISSUE THREAD

**Issue by omlet05** [mindw/elasticsearch-prometheus-exporter#30]
Hey,

Could you release the plugin for 8.8.0?

Thank you for all your work!
Regards,

**Comment by mindw** [comment]
I've tried and run into some issues https://github.com/elastic/elasticsearch/issues/96360 .
Since it also introduced breaking API changes which need to be tested :(

**Comment by Philippus** [comment]
I think skipping 8.8.0 and going to 8.8.1 should work.

**Comment by mindw** [comment]
@Philippus 8.8.1.0 and 8.8.2.0 have been released. please report any issue!
