### ISSUE TITLE
Release 8.11.4

### ISSUE THREAD

**Issue by foal** [mindw/elasticsearch-prometheus-exporter#49]
Hey,

Could you release the plugin for 8.11.4? Or can I use the plugin 8.11.3 with ES 8.11.4?

Thank you for all your work!
Regards,

**Comment by mindw** [comment]
Yes, sorry - was a bit busy. I'll release a new version within a couple of day.

**Comment by mindw** [comment]
@foal 8.11.3.0 and 8.12.0.0 were both release. Please report any issues you may encounter.
