### ISSUE TITLE
Exporter for 8.13.0

### ISSUE THREAD

**Issue by ewolfman** [mindw/elasticsearch-prometheus-exporter#56]
Hello,

Can you please release for v8.13.0?

Thanks.

**Comment by Philippus** [comment]
Probably should skip that one, and go for 8.13.2 immediately.

**Comment by mindw** [comment]
This new version has introduced breaking changes to plugin API, Gradle build and possibly others. I've already spent several hours on trying to get this to build/work.
I'll give it another shot during the weekend.
Any help is appreciated!

**Comment by mindw** [comment]
@Philippus @ewolfman , please https://github.com/mindw/elasticsearch-prometheus-exporter/releases/tag/8.13.2.0 .
Please open new issues in case of trouble.

**Comment by Philippus** [comment]
I'll try it out, elasticsearch is notorious for their breaking changes for plugins. :(
