### ISSUE TITLE
Cluster state request failed after upgrade to ES 8.15.1

### ISSUE THREAD

**Issue by Philippus** [mindw/elasticsearch-prometheus-exporter#64]
We are getting the error below after upgrading from Elasticsearch 8.14.3 to 8.15.1:

```json
{
  "error": {
    "root_cause": [
      {
        "type": "exception",
        "reason": "Cluster state request failed"
      }
    ],
    "type": "exception",
    "reason": "Cluster state request failed",
    "caused_by": {
      "type": "array_index_out_of_bounds_exception",
      "reason": "Index 0 out of bounds for length 0"
    }
  },
  "status": 500
}
```

**Comment by mindw** [comment]
need to look into this, tests have passed so the issue is perhaps some new state ES added. 🤦🏻‍♂️

**Comment by Philippus** [comment]
Not sure yet, but we think it could be an issue that was fixed in https://github.com/elastic/elasticsearch/pull/112720. Because we also don't get any stats on a GET `_nodes/stats` call.

**Comment by mindw** [comment]
@Philippus thanks for digging into this - sure saved a lot of digging!

Guess the fix is 8.15.2 - I'll try to get a release as soon as its available.

**Comment by Philippus** [comment]
8.15.2 indeed fixes the issue with the `_nodes/stats` call.

**Comment by mindw** [comment]
@Philippus plugin version 8.15.2.0 was release - can you please verify it solves this issue?

**Comment by Philippus** [comment]
I think this can be closed, I'm 99% this issue is solved. However, we have migrated our setup to use https://github.com/prometheus-community/elasticsearch_exporter ourselves, so I'm unable to verify.

**Comment by mindw** [comment]
@Philippus thank you for the update. Given the pain ES plugins are, your decision to migrate makes a lot of sense. https://github.com/vinted/elasticsearch-exporter-rs is another alternative.
