### ISSUE TITLE
Exporter for 7.17.25 version do not have correct release assets

### ISSUE THREAD

**Issue by vashkevich** [mindw/elasticsearch-prometheus-exporter#67]
Hello guys,
Thank you for building this amazing prometheus exporter for elasticsearch. Could you be so kind to take a look at 7.17.25 exporter release and rebuild it to have both source and zip package to install - https://github.com/mindw/elasticsearch-prometheus-exporter/releases/tag/7.17.25.0. For https://github.com/mindw/elasticsearch-prometheus-exporter/releases/tag/7.17.24.0 everything is fine.

Thanks!

**Comment by mindw** [comment]
@vashkevich thanks for the head's up!

The release was re-created and now includes the compiled plugin.
